media_folder: src/assets/images # Location where files will be stored in the repo
public_folder: src/assets/images # The src attribute for uploaded media
local_backend: true # set to true to allow decap cms to save file locally during development
backend:
  name: git-gateway
  repo: codyrushing/rushtopfish
  branch: main
# https://decapcms.org/docs/widgets/#select
collections:
  - name: page # Used in routes, e.g., /admin/collections/blog
    label: Page # Used in the UI
    # slug: "{{fields.slug}}"
    folder: src/content/pages # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - name: title
        label: Title
        widget: string

      - name: slug
        label: Slug
        widget: string
        hint: Page slug - use "index" for home page

      - name: description
        label: Description
        widget: text

      - name: banner
        label: Banner
        widget: object
        required: false
        fields:
          - name: hidden
            label: Hidden
            widget: boolean
            required: false
          - name: extra_classes
            label: extra_classes
            widget: string
            required: false
          - name: content
            label: Content
            widget: markdown
            required: false

      - name: sections
        label: Page sections
        widget: list
        slug: "{{fields.name}}"
        summary: "{{fields.title}}"
        fields:
          - name: title
            label: Name
            widget: string

          - name: heading
            label: Heading text
            widget: string
            required: false

          - name: linkable
            label: Linkable?
            widget: boolean
            required: false

          - name: size
            label: Size
            widget: select
            required: false
            default: [auto]
            options: [auto, full_screen]

          - name: content_blocks
            label: Content blocks
            widget: list
            required: false
            types:
              - label: Rich text
                name: rich_text
                widget: object
                fields:
                  - label: Rich text content
                    name: content
                    widget: markdown
                  - label: Content style
                    name: content_style
                    widget: select
                    options: ["light", "dark"]
                    required: false
                  - label: Content background
                    name: content_background
                    widget: boolean
                    required: false
                  - label: Extra classes
                    name: extra_classes
                    widget: string
                    required: false

              - label: Aside content
                name: aside
                hint: Add an image along side some content
                widget: object
                fields:
                  - name: image
                    label: Image
                    widget: image
                    required: false

                  - name: alt
                    label: Image Alt
                    widget: string
                    required: false

                  - name: caption
                    label: Caption
                    widget: markdown
                    required: false

                  - name: image_extra_classes
                    label: Image extra classes
                    widget: string
                    required: false

                  - name: content
                    label: Content
                    widget: markdown
                    required: false

                  - name: content_extra_classes
                    label: Content extra classes
                    widget: string
                    required: false

                  - name: image_aspect_ratio
                    label: Image aspect ratio
                    widget: select
                    options:
                      - label: "None"
                        value: "aspect-auto"
                      - label: "1x1"
                        value: "aspect-square"
                      - label: "3x2"
                        value: "aspect-3/2"
                    required: false

                  - name: x_pos
                    label: Horizontal position
                    widget: number
                    default: 50
                    value_type: "int"
                    hint: 0 is left, 50 is center, 100 is right
                    step: 1
                    required: false

                  - name: y_pos
                    label: Vertical position
                    widget: number
                    default: 50
                    value_type: "int"
                    hint: 0 is top, 50 is center, 100 is bottom
                    step: 1
                    required: false

              - label: Newsletter signup
                name: newsletter_signup
                widget: object
                fields:
                  - label: Show newsletter signup form
                    name: show_signup_form
                    widget: boolean
                    required: false

          - name: content_style
            label: Content style
            widget: select
            options: [light, dark]
            required: false

          - name: content_background
            label: Content background
            widget: boolean
            required: false

          - name: x_pos
            label: Content horizontal position
            widget: select
            options: [left, center, right]
            required: false

          - name: y_pos
            label: Content vertical position
            widget: select
            options: [top, center, bottom]
            required: false

          - name: extra_classes
            label: Extra classes
            widget: string
            required: false

          - name: background_color
            label: Background color
            required: false
            widget: color

          - name: images
            label: Media
            widget: list
            fields:
              - name: image
                label: Image
                widget: image

              - name: fit
                label: Fit
                widget: select
                required: false
                options: [contain, cover, fill, none]

              - name: x_pos
                label: Horizontal position
                widget: number
                default: 50
                value_type: "int"
                hint: 0 is left, 50 is center, 100 is right
                step: 1
                required: false

              - name: y_pos
                label: Vertical position
                widget: number
                default: 50
                value_type: "int"
                hint: 0 is top, 50 is center, 100 is bottom
                step: 1
                required: false

              - name: alt
                label: Alt
                required: false
                hint: Short description of image
                widget: string

              - name: caption
                label: Caption
                required: false
                hint: eg. photo credit
                widget: markdown

          - name: image_presentation
            label: Image presentation
            hint: Only applies when using multiple images
            widget: select
            required: false
            options: [carousel, grid]

          - name: parallax
            label: Parallax scroll
            widget: boolean
            required: false
