media_folder: src/assets/images # Location where files will be stored in the repo
public_folder: src/assets/images # The src attribute for uploaded media
local_backend: true # set to true to allow decap cms to save file locally during development
backend:
  name: git-gateway
  repo: codyrushing/rushtopfish
  branch: main
# https://decapcms.org/docs/widgets/#select
collections:
  - name: page # Used in routes, e.g., /admin/collections/blog
    label: Page # Used in the UI
    # slug: "{{fields.slug}}"
    folder: src/content/pages # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - name: title
        label: Title
        widget: string

      - name: slug
        label: Slug
        widget: string
        hint: Page slug - use "index" for home page

      - name: description
        label: Description
        widget: text

      - name: sections
        label: Page sections
        widget: list
        slug: "{{fields.slug}}"
        summary: "{{fields.title}}"
        fields:
          - name: title
            label: Name
            widget: string

          - name: linkable
            label: Linkable?
            widget: boolean

          - name: size
            label: Size
            widget: select
            required: false
            default: [auto]
            options: [auto, full_screen]

          - name: newsletter_signup
            label: Newsletter signup
            widget: boolean
            required: false

          - name: content
            label: Content
            widget: markdown
            required: false

          - name: content_style
            label: Content style
            widget: select
            options: [light, dark]
            required: false

          - name: x_pos
            label: Content horizontal position
            widget: select
            options: [left, center, right]
            required: false

          - name: y_pos
            label: Content vertical position
            widget: select
            options: [top, center, bottom]
            required: false

          - name: content_background
            label: Content background
            widget: boolean
            required: false

          - name: extra_classes
            label: Extra classes
            widget: string
            required: false

          - name: background_color
            label: Background color
            required: false
            widget: color

          - name: images
            label: Media
            widget: list
            fields:
              - name: image
                label: Image
                widget: image

              - name: fit
                label: Fit
                widget: select
                required: false
                options: [contain, cover, fill, none]

              - name: x_pos
                label: Horizontal position
                widget: number
                default: 50
                value_type: "int"
                hint: 0 is left, 50 is center, 100 is right
                step: 1
                required: false

              - name: y_pos
                label: Vertical position
                widget: number
                default: 50
                value_type: "int"
                hint: 0 is top, 50 is center, 100 is bottom
                step: 1
                required: false

              - name: alt
                label: Alt
                required: false
                hint: Short description of image
                widget: string

              - name: caption
                label: Caption
                required: false
                hint: eg. photo credit
                widget: markdown

          - name: image_presentation
            label: Image presentation
            hint: Only applies when using multiple images
            widget: select
            required: false
            options: [carousel, grid]

          - name: parallax
            label: Parallax scroll
            widget: boolean
            required: false
